sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t krishnakotadocker/docker-basic -f Dockerfile.dev .

script:
  - docker run -e CI=true krishnakotadocker/docker-basic npm run test
