sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t krishnakotadocker/docker-basic -f Dockerfile.dev .

script:
  - docker run -e CI=true krishnakotadocker/docker-basic npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-basic"
  env: "DockerBasic-env"
  bucket-name: "elasticbeanstalk-ap-south-1-898404873516"
  bucket-path: "docker-basic"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
