sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t krishnadwypayan/docker-basic -f Dockerfile.dev .

script:
  - docker exec -e CI=true krishnadwypayan/docker-basic npm run test
